"""
engine.engine
~~~~~~~~~~~~~
Engine — the core singleton. Foundation of everything.

Key design rules (non-negotiable):
  1. Singleton — created once by Runner, never recreated per request.
  2. Receives injected infrastructure (redis, db, s3). NEVER creates them.
  3. Creates BillManager and UsageTracker internally.
  4. BillManager NEVER leaves Engine.
  5. UsageTracker exposed as engine.usage_tracker (the only billing-adjacent object that leaves).
  6. Engine controls the full execution flow — ResumeCheck hooks fire through Engine, not themselves.
  7. On AgentCaller exception: catch → ErrorHandler.alert() → set status FAIL → dump → done.
  8. trigger_run() takes an Agent object (not raw components) — Runner builds and passes it.

Execution flow (from arch):
  trigger_run(params, agent) →
    resume check (status → hitl | queue/created | resume) →
    execution loop (bill check → interrupt check → ExecutionStep.run → checkpoint) →
    post execution (error or status set) →
    dump data (redis → s3, metadata on db) →
    webhook (if enabled)
"""

from __future__ import annotations

import asyncio
from typing import Any

import redis.asyncio as aioredis
from agent_sdk.agent import Agent
from agent_sdk.execution_step import StepContext, StepStatus
from loguru import logger
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker

from engine.bill_manager import BillManager
from engine.error_handler import AlertContext, ErrorHandler
from engine.execution_manager import ExecutionManager
from engine.types import ExecutionState, RunStatus, TriggerParams
from engine.usage_tracker import UsageTracker

# Maximum iterations safety cap (absolute hard cap regardless of agent config)
_MAX_ITERATIONS_HARD_CAP = 200


class Engine:
    """
    Core execution singleton. Created once by Runner at startup.

    Args:
        redis:          Async Redis client (injected by Runner)
        db_engine:      SQLAlchemy async engine (injected by Runner)
        s3_client:      boto3 S3 client (injected by Runner)
        s3_bucket:      S3/MinIO bucket name
        default_budget: Default credit budget per run
    """

    def __init__(
        self,
        redis: aioredis.Redis,
        db_engine: AsyncEngine,
        s3_client: Any,
        s3_bucket: str = "agent-runs",
        default_budget: float = 10.0,
    ) -> None:
        self._redis = redis
        self._db_engine = db_engine
        self._s3 = s3_client

        # DB session factory
        self._db_session_factory: async_sessionmaker[AsyncSession] = async_sessionmaker(
            db_engine, expire_on_commit=False
        )

        # Internal components — BillManager NEVER leaves this class
        self._bill_manager = BillManager(redis=redis, default_budget=default_budget)

        # UsageTracker is the ONLY thing that leaves Engine (as engine.usage_tracker)
        self._usage_tracker = UsageTracker(
            bill_manager=self._bill_manager,
            db_session_factory=self._db_session_factory,
        )

        # Other internal components
        self._execution_manager = ExecutionManager(
            redis=redis,
            db_session_factory=self._db_session_factory,
            s3_client=s3_client,
            s3_bucket=s3_bucket,
        )
        self._error_handler = ErrorHandler()

        logger.info("Engine: initialized (singleton) | bucket={}", s3_bucket)

    @property
    def usage_tracker(self) -> UsageTracker:
        """
        The ONLY billing-adjacent object that leaves Engine.
        Runner injects this into all AgentCaller instances.
        """
        return self._usage_tracker

    # ------------------------------------------------------------------
    # Main entry point — called by Runner
    # ------------------------------------------------------------------

    async def trigger_run(
        self,
        params: TriggerParams,
        agent: Agent,
    ) -> ExecutionState:
        """
        Full execution flow for one agent run.
        Runner calls this with the Agent object fully wired (deps injected).

        Returns the final ExecutionState (for Runner to send response).
        """
        logger.info(
            "Engine: trigger_run | agent={} org={} session={} stream={}",
            params.agent_id,
            params.org_id,
            params.session_id,
            params.stream,
        )

        # Build initial state — run_id comes from params (pre-generated by caller)
        # so fire-and-forget clients can poll immediately with the returned run_id.
        #
        # max_iterations: prefer TriggerParams override (per-request cap), else
        # agent's AgentProfile setting, else ExecutionState default (50).
        _profile_max_iter = getattr(
            getattr(agent.runner, "agent_profile", None),
            "max_iterations",
            50,
        )
        _effective_max_iter = (
            params.max_iterations
            if params.max_iterations is not None
            else _profile_max_iter
        )
        state = ExecutionState(
            run_id=params.run_id,
            org_id=params.org_id,
            proj_id=params.proj_id,
            session_id=params.session_id,
            idem_key=params.idem_key,
            agent_id=params.agent_id,
            messages=list(params.messages),
            stream=params.stream,
            webhook=params.webhook,
            webhook_config=params.webhook_config,
            max_iterations=_effective_max_iter,
        )

        # Inject run context into UsageTracker (so all logs are tagged with this run)
        self._usage_tracker.set_run_context(
            {
                "org_id": params.org_id,
                "proj_id": params.proj_id,
                "session_id": params.session_id,
                "run_id": state.run_id,
                "agent_id": params.agent_id,
                "idem_key": params.idem_key,
            }
        )

        # Load budget for this org/run
        await self._bill_manager.load_budget(params.org_id, state.run_id)

        # Store webhook entry if needed
        if params.webhook and params.webhook_config:
            await self._execution_manager.store_webhook_entry(
                org_id=params.org_id,
                run_id=state.run_id,
                session_id=params.session_id,
                config=params.webhook_config,
            )

        # --- RESUME CHECK ---
        should_run = await self._run_resume_check(state, agent)
        if not should_run:
            if state.status == RunStatus.HITL:
                # HITL can wait hours or days — far beyond Redis TTL.
                # Dump state to DB + S3 now so it survives expiry and can be restored.
                logger.info(
                    "Engine: HITL pending — dumping state for long-term persistence | run={}",
                    state.run_id,
                )
                await self._execution_manager.dump_data(state)
            else:
                # DONE or FAIL — already completed, don't re-dump.
                logger.info(
                    "Engine: run={} already {} — skipping re-run",
                    state.run_id,
                    state.status.value,
                )
            return state

        # --- EXECUTION LOOP ---
        try:
            state = await self._run_execution_loop(state=state, agent=agent)
        except Exception as error:
            # Unrecoverable error from AgentCaller (already re-raised from inside loop)
            alert_ctx = AlertContext(
                org_id=state.org_id,
                run_id=state.run_id,
                session_id=state.session_id,
                agent_id=state.agent_id,
                iteration=state.iteration,
            )
            self._error_handler.alert(error, alert_ctx)
            state.status = RunStatus.FAIL
            state.error = str(error)
        finally:
            # --- POST EXECUTION: set final status ---
            if state.status == RunStatus.WIP:
                # Loop ended without an explicit status set — treat as complete
                state.status = RunStatus.DONE
            await self._execution_manager.set_status(state.run_id, state.status)

            logger.info(
                "Engine: run={} finished | status={} iter={}",
                state.run_id,
                state.status.value,
                state.iteration,
            )

            # --- DUMP DATA ---
            await self._execution_manager.dump_data(state)

            # Final budget sync to Redis
            await self._bill_manager.sync_records(state.org_id, state.run_id)

        # --- WEBHOOK ---
        if params.webhook:
            await self._dispatch_webhooks(state)

        return state

    # ------------------------------------------------------------------
    # Resume check — Engine controls flow, ResumeCheck provides hooks
    # ------------------------------------------------------------------

    async def _run_resume_check(self, state: ExecutionState, agent: Agent) -> bool:
        """
        Execute resume check logic. Engine owns this control flow.
        agent.resume_check hooks are called here — Engine decides what to do with return values.

        Returns True if the execution loop should run, False if it should be skipped.
        """
        resume_check = agent.resume_check
        current_status = await self._execution_manager.get_status(state.run_id)
        state.status = current_status

        logger.debug(
            "Engine: resume_check | run={} current_status={}",
            state.run_id,
            current_status.value,
        )

        if current_status == RunStatus.HITL:
            hitl_actions = await self._execution_manager.load_hitl_actions(state.run_id)
            state.checkpoint_data["hitl_actions"] = hitl_actions
            completed = resume_check.hitl_action(state)
            if not completed:
                logger.info(
                    "Engine: HITL pending | run={} — loop skipped", state.run_id
                )
                return False  # WIP never set, loop won't run

        elif current_status in (RunStatus.QUEUE, RunStatus.CREATED):
            logger.info("Engine: first run | run={}", state.run_id)
            resume_check.initial_work(state)

        elif current_status not in (RunStatus.DONE, RunStatus.FAIL):
            # Resuming from interrupt/checkpoint
            logger.info(
                "Engine: resuming | run={} from_status={}",
                state.run_id,
                current_status.value,
            )
            restored = await self._execution_manager.checkpoint_restore(state.run_id)
            if restored is not None:
                state.messages = restored.messages
                state.iteration = restored.iteration
                state.checkpoint_data = restored.checkpoint_data
                logger.debug(
                    "Engine: checkpoint restored | run={} iter={}",
                    state.run_id,
                    state.iteration,
                )
            resume_check.resume_work(state)

        # Already done or failed — do not re-run
        if current_status in (RunStatus.DONE, RunStatus.FAIL):
            logger.info(
                "Engine: run={} already {} — skipping re-run",
                state.run_id,
                current_status.value,
            )
            return False

        # Unconditional pre-loop hook (fires on first run AND resume)
        resume_check.before_run(state)

        # Engine sets WIP AFTER before_run returns
        state.status = RunStatus.WIP
        await self._execution_manager.set_status(state.run_id, RunStatus.WIP)
        logger.info("Engine: run={} → WIP | loop starting", state.run_id)
        return True

    # ------------------------------------------------------------------
    # Execution loop
    # ------------------------------------------------------------------

    async def _run_execution_loop(
        self,
        state: ExecutionState,
        agent: Agent,
    ) -> ExecutionState:
        """
        The execution loop. Runs while status == WIP.

        Each iteration:
          [1] Bill check → stop if budget exceeded
          [2] Status check → break on interrupt/hitl
          [3] ExecutionStep.run() ← Agent SDK / developer takes over here
          [4] Periodic checkpoint dump (every N iterations)
          [5] Break on COMPLETE / ERROR / INTERRUPTED
        """
        hard_cap = min(state.max_iterations, _MAX_ITERATIONS_HARD_CAP)

        while state.iteration < hard_cap:
            state.iteration += 1

            logger.debug(
                "Engine: loop iter={}/{} | run={}",
                state.iteration,
                hard_cap,
                state.run_id,
            )

            # [1] Bill check — fast local check
            if self._bill_manager.is_budget_exceeded():
                logger.warning(
                    "Engine: budget exceeded | run={} iter={} remaining={:.4f}",
                    state.run_id,
                    state.iteration,
                    self._bill_manager.get_remaining_budget(),
                )
                state.status = RunStatus.FAIL
                state.error = "Budget exceeded"
                break

            # [2] External interrupt / HITL check (Redis poll)
            live_status = await self._execution_manager.get_status(state.run_id)
            if live_status in (RunStatus.INTERRUPT, RunStatus.HITL):
                logger.info(
                    "Engine: external {} detected | run={} iter={}",
                    live_status.value,
                    state.run_id,
                    state.iteration,
                )
                state.status = live_status
                break

            # [3] ExecutionStep.run() — developer's code takes over
            # Build StepContext from Engine state (engine types don't leak into agent-sdk)
            step_context = StepContext(
                messages=state.messages,
                stream=state.stream,
                iteration=state.iteration,
                state_data=dict(state.checkpoint_data),
            )
            try:
                step_result = await agent.execution_step.run(
                    agent_runner=agent.runner,
                    agent_context=agent.agent_context,
                    context=step_context,
                )
            except Exception:
                # Re-raise — outer try/except handles alerting + status set
                raise

            # Update messages from step result
            state.messages = step_result.messages

            # Capture final output if step is complete
            if step_result.output is not None:
                state.result = step_result.output

            # Merge any state_data updates from the step into checkpoint_data
            if step_result.state_data is not None:
                state.checkpoint_data.update(step_result.state_data)

            # [4] Periodic checkpoint dump (every N iterations)
            await self._execution_manager.periodic_dump(state)

            # Periodic budget sync to Redis (every 10 iterations)
            if state.iteration % 10 == 0:
                await self._bill_manager.sync_records(state.org_id, state.run_id)

            # [5] Break conditions
            if step_result.status == StepStatus.COMPLETE:
                logger.info(
                    "Engine: COMPLETE | run={} iter={}", state.run_id, state.iteration
                )
                state.status = RunStatus.DONE
                break

            if step_result.status == StepStatus.ERROR:
                # Read step_result.error first (explicit field), fall back to
                # metadata["error"] for backward compatibility with old steps.
                step_error = step_result.error or step_result.metadata.get(
                    "error", "ExecutionStep returned ERROR"
                )
                logger.error(
                    "Engine: step ERROR | run={} iter={} error={}",
                    state.run_id,
                    state.iteration,
                    step_error,
                )
                state.status = RunStatus.FAIL
                state.error = step_error
                break

            if step_result.status == StepStatus.INTERRUPTED:
                logger.info(
                    "Engine: step INTERRUPTED | run={} iter={}",
                    state.run_id,
                    state.iteration,
                )
                state.status = RunStatus.INTERRUPT
                break

            # StepStatus.CONTINUE → keep looping

        else:
            # While-loop exhausted (iterations reached hard_cap without break)
            logger.warning(
                "Engine: max_iterations={} reached without completion | run={}",
                hard_cap,
                state.run_id,
            )
            state.status = RunStatus.FAIL
            state.error = f"Max iterations ({hard_cap}) reached without completion"

        return state

    # ------------------------------------------------------------------
    # Webhook dispatch
    # ------------------------------------------------------------------

    async def _dispatch_webhooks(self, state: ExecutionState) -> None:
        """
        Fetch org webhook entries from DB and send notifications.
        Passes headers and signature config from stored entries.
        V1: best-effort. V2: retry via separate queue-based sender.
        """
        entries = await self._execution_manager.fetch_org_webhook_entries(
            org_id=state.org_id,
            run_id=state.run_id,
        )
        logger.debug(
            "Engine: dispatching webhooks | run={} count={}", state.run_id, len(entries)
        )
        for entry in entries:
            await self._execution_manager.send_webhook(
                session_id=state.session_id,
                run_id=state.run_id,
                status=state.status.value,
                url=entry["url"],
                headers=entry.get("headers") or {},
                signature_header=entry.get("signature_header"),
                signature_secret=entry.get("signature_secret"),
                signature_algorithm=entry.get("signature_algorithm"),
            )

    # ------------------------------------------------------------------
    # Dump queue — delegation for Runner's background worker
    # ------------------------------------------------------------------

    async def process_dump_queue(self, batch_size: int = 10) -> int:
        """
        Drain the async S3 dump queue. Called periodically by Runner's dump worker.
        Loads each run's checkpoint from Redis and uploads to S3 via asyncio.to_thread.
        Returns number of items processed.
        """
        return await self._execution_manager.process_dump_queue(batch_size=batch_size)

    # ------------------------------------------------------------------
    # DB schema setup (called at startup by Runner)
    # ------------------------------------------------------------------

    async def setup_db(self) -> None:
        """
        Create all DB tables and apply incremental schema migrations.
        Called once at startup by Runner.

        Two-phase:
          1. create_all  — creates any tables that don't yet exist (new deploys)
          2. run_migrations — applies ALTER TABLE statements for columns added
             after initial table creation (handles existing deploys)
        """
        from engine.db import Base, run_migrations

        async with self._db_engine.begin() as conn:
            # Phase 1: create missing tables
            await conn.run_sync(Base.metadata.create_all)
            # Phase 2: apply incremental column/index migrations
            await run_migrations(conn)

        logger.info("Engine: DB tables created/verified + migrations applied")

